controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
product_send_message:
    path: /send-message
    controller: App\Controller\ProductController::sendMessage
